// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJF4b90XhUbK6X3u-KRuPDoKLdQEioH3w',
    appId: '1:205932736763:web:922a281d5574ac0014405e',
    messagingSenderId: '205932736763',
    projectId: 'strumly-fb446',
    authDomain: 'strumly-fb446.firebaseapp.com',
    storageBucket: 'strumly-fb446.firebasestorage.app',
    measurementId: 'G-78YZ6WP4W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLUh-7cafRR8pvalRSqQ6wTuE2hwlHBM',
    appId: '1:205932736763:android:f40773898d3e6cde14405e',
    messagingSenderId: '205932736763',
    projectId: 'strumly-fb446',
    storageBucket: 'strumly-fb446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRGKgFknzv4_ysv8VP423_wvUFqaxH0tU',
    appId: '1:205932736763:ios:b9764b74728d91e314405e',
    messagingSenderId: '205932736763',
    projectId: 'strumly-fb446',
    storageBucket: 'strumly-fb446.firebasestorage.app',
    iosClientId: '205932736763-n5rso0m09egnhcebrfifrc0vhvt0ou9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.strumly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRGKgFknzv4_ysv8VP423_wvUFqaxH0tU',
    appId: '1:205932736763:ios:b9764b74728d91e314405e',
    messagingSenderId: '205932736763',
    projectId: 'strumly-fb446',
    storageBucket: 'strumly-fb446.firebasestorage.app',
    iosClientId: '205932736763-n5rso0m09egnhcebrfifrc0vhvt0ou9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.strumly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJF4b90XhUbK6X3u-KRuPDoKLdQEioH3w',
    appId: '1:205932736763:web:f8e764dcc3339c3a14405e',
    messagingSenderId: '205932736763',
    projectId: 'strumly-fb446',
    authDomain: 'strumly-fb446.firebaseapp.com',
    storageBucket: 'strumly-fb446.firebasestorage.app',
    measurementId: 'G-WN80X68SZ2',
  );
}
